-- core/localization/es/testing_es.lua
return {
    dialogueTest1_intro_1      = "Oh, un viajero! No habia visto a nadie en mucho tiempo.",
    dialogueTest1_intro_2      = "Que te trae por aqui?",
    dialogueTest1_option_intro = "Hay algo que quieras contarme?",
    dialogueTest1_1            = "Tengo algo importante que contarte.",
    dialogueTest1_2            = "Que camino deseas tomar?",
    dialogueTest1_3            = "Sabio. El camino del norte es mas seguro pero largo.",
    dialogueTest1_4            = "Valiente. El paso del este es mas rapido pero peligroso.",
    dialoguePlayerTest1_1      = "Hablame del camino del norte.",
    dialoguePlayerTest1_2      = "Hablame del paso del este.",
    npc_opt_story              = "El Camino del Norte",
    SimpleTalkOptionTEST1      = "PRUEBA DE DIALOGO SIMPLE",
    test_item_a                = "Llave de Hierro",
    test_item_a_desc           = "Una vieja llave oxidada. Solo cabe una por espacio.",
    test_item_b                = "Pocion de Vida",
    test_item_b_desc           = "Restaura algo de vida. Se puede apilar.",
    test_mission_item          = "Pergamino Antiguo",
    test_mission_item_desc     = "Un pergamino con un algoritmo olvidado.",
    mission_test_1_name        = "Mision de Prueba",
    mission_test_1_desc        = "Una mision para probar el sistema.",
    test_task_1_name           = "Tarea de Prueba 1",
    test_task_1_desc           = "Completa la primera tarea de prueba.",
    test_task_2_name           = "Tarea de Prueba 2",
    test_task_2_desc           = "Completa la segunda tarea de prueba.",
}